spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: rajdeep123
#  jwtExpirationInMillis: 0
  jwtExpirationInMillis: 9000000
  refreshTokenExpirationInMillis: 21600000