spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  username: ${REDIS_USERNAME}
  password: ${REDIS_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: rajdeep123
#  jwtExpirationInMillis: 0
  jwtExpirationInMillis: 9000000
  refreshTokenExpirationInMillis: 21600000

konsign:
  cookie:
    maxAge: 604800
    httpOnly: true
    cookiePath: "/"