name: Build Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PORT: 8080

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Building docker image
        run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/konsign-api:${{ github.ref_name }}.${{ github.sha }} .
      - name: Pushing docker image to dockerhub
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/konsign-api:${{ github.ref_name }}.${{ github.sha }}
